"""empty message

Revision ID: aa6fb3d39acf
Revises: 65f38e1dc6fe
Create Date: 2022-02-03 18:58:22.681053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa6fb3d39acf'
down_revision = '65f38e1dc6fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
